language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t jal24/docker-react -f dockerfile.dev .

script:
        - run -e CI=true jal24/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: ""
        app: "docker-react"
        env: "Docker-env"
        bucket_name:  ""
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id:  $AWS_ACCESS_KEY
        secret_access_key: "$AWS_SECRET_KEY"